name: Deploy App

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/666837127066/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-actions-sa@gcp-devops-minikube-487813.iam.gserviceaccount.com"

    - uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Image
      run: |
        docker build -t us-central1-docker.pkg.dev/gcp-devops-minikube-487813/python-repo/python-app:latest -f dev/Dockerfile .

    - name: Push Image
      run: |
        docker push us-central1-docker.pkg.dev/gcp-devops-minikube-487813/python-repo/python-app:latest

    - name: Deploy to Minikube VM
      run: |
        # Copy YAML to VM
        gcloud compute scp dev/k8s.yaml minikube-vm:~/k8s.yaml --zone=us-central1-a

        # SSH and deploy
        gcloud compute ssh minikube-vm --zone=us-central1-a --command "
          # Ensure lock folder exists
          sudo mkdir -p /tmp/minikube-locks
          sudo chmod -R 777 /tmp/minikube-locks

          # Delete old cluster if it exists
          sudo minikube delete

          # Start new lightweight cluster
          sudo minikube start --driver=docker --memory=2000 --cpus=2 --kubernetes-version=v1.24.0 --wait=all

          # Export KUBECONFIG explicitly
          export KUBECONFIG=/root/.kube/config

          # Apply Kubernetes manifests
          sudo minikube kubectl -- apply -f ~/k8s.yaml --insecure-skip-tls-verify
        "
